name: Tests
on: [push]

jobs:
  ruby:
    name: Ruby Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "3.0", "3.1", "3.2", "3.3" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run Tests
        run: bundle exec rake test
